% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={lab\_deliverable\_2},
  pdfauthor={Yihang Duanmu, Minjun Kim, Annelise Schreiber},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{lab\_deliverable\_2}
\author{Yihang Duanmu, Minjun Kim, Annelise Schreiber}
\date{2025-10-01}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse); }\FunctionTok{library}\NormalTok{(broom); }\FunctionTok{library}\NormalTok{(kableExtra); }\FunctionTok{library}\NormalTok{(here); }\FunctionTok{library}\NormalTok{(janitor); }\FunctionTok{library}\NormalTok{(lubridate); }\FunctionTok{library}\NormalTok{(readr); }\FunctionTok{library}\NormalTok{(dplyr); }\FunctionTok{library}\NormalTok{(emmeans); }\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

First, install the necessary packages.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# UCI Facebook file is semicolon{-}separated}
\NormalTok{fb\_raw }\OtherTok{\textless{}{-}}\NormalTok{ readr}\SpecialCharTok{::}\FunctionTok{read\_delim}\NormalTok{(}\StringTok{"dataset\_Facebook.csv"}\NormalTok{, }\AttributeTok{delim =} \StringTok{";"}\NormalTok{, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Standardize names and coerce a few key fields}
\NormalTok{fb }\OtherTok{\textless{}{-}}\NormalTok{ fb\_raw }\SpecialCharTok{|\textgreater{}}
\NormalTok{  janitor}\SpecialCharTok{::}\FunctionTok{clean\_names}\NormalTok{() }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{post\_month   =} \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.integer}\NormalTok{(post\_month)),}
    \AttributeTok{post\_weekday =} \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.integer}\NormalTok{(post\_weekday)),}
    \AttributeTok{post\_hour    =} \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.integer}\NormalTok{(post\_hour)),}
    \AttributeTok{paid         =} \FunctionTok{if\_else}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(paid), }\DecValTok{0}\DataTypeTok{L}\NormalTok{, }\FunctionTok{as.integer}\NormalTok{(paid)),}
    \AttributeTok{lifetime\_post\_consumers =} \FunctionTok{as.numeric}\NormalTok{(lifetime\_post\_consumers)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

Load the csv file and standardize the column names.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fb2 }\OtherTok{\textless{}{-}}\NormalTok{ fb }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{post\_weekday\_num =}\NormalTok{ post\_weekday,}
    \AttributeTok{post\_hour\_num    =}\NormalTok{ post\_hour,}
    \AttributeTok{post\_month\_num   =}\NormalTok{ post\_month}
\NormalTok{  )}

\CommentTok{\# Weekday factor (1–7 expected)}
\NormalTok{wk\_labels }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Mon"}\NormalTok{,}\StringTok{"Tue"}\NormalTok{,}\StringTok{"Wed"}\NormalTok{,}\StringTok{"Thu"}\NormalTok{,}\StringTok{"Fri"}\NormalTok{,}\StringTok{"Sat"}\NormalTok{,}\StringTok{"Sun"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{all}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_weekday\_num)) }\SpecialCharTok{\&\&} \FunctionTok{all}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_weekday\_num }\SpecialCharTok{\%in\%} \DecValTok{1}\SpecialCharTok{:}\DecValTok{7}\NormalTok{)) \{}
\NormalTok{  wday\_fac }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_weekday\_num, }\AttributeTok{levels =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\AttributeTok{labels =}\NormalTok{ wk\_labels, }\AttributeTok{ordered =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \CommentTok{\# fallback if strings slipped through}
\NormalTok{  wday\_fac }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{as.character}\NormalTok{(fb}\SpecialCharTok{$}\NormalTok{post\_weekday), }\AttributeTok{ordered =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{\}}

\CommentTok{\# Hour factor: detect actual range (handles 0–23 or 1–23)}
\NormalTok{hour\_levels }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{unique}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_hour\_num[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_hour\_num)]))}
\NormalTok{hour\_fac }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_hour\_num, }\AttributeTok{levels =}\NormalTok{ hour\_levels, }\AttributeTok{ordered =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Month factor (1–12 {-}\textgreater{} Jan..Dec)}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{all}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_month\_num)) }\SpecialCharTok{\&\&} \FunctionTok{all}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_month\_num }\SpecialCharTok{\%in\%} \DecValTok{1}\SpecialCharTok{:}\DecValTok{12}\NormalTok{)) \{}
\NormalTok{  month\_fac }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fb2}\SpecialCharTok{$}\NormalTok{post\_month\_num, }\AttributeTok{levels =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{12}\NormalTok{, }\AttributeTok{labels =}\NormalTok{ month.abb, }\AttributeTok{ordered =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  month\_fac }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fb}\SpecialCharTok{$}\NormalTok{post\_month, }\AttributeTok{ordered =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{\}}

\CommentTok{\# Paid flag as tidy factor}
\NormalTok{paid\_fac }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{if\_else}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(fb}\SpecialCharTok{$}\NormalTok{paid) }\SpecialCharTok{|}\NormalTok{ fb}\SpecialCharTok{$}\NormalTok{paid }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\StringTok{"Unpaid"}\NormalTok{, }\StringTok{"Paid"}\NormalTok{),}
                   \AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Unpaid"}\NormalTok{,}\StringTok{"Paid"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

This block standardizes your time and paid fields for modeling. First,
it builds fb2 by safely coercing post\_weekday, post\_hour, and
post\_month to integers (silently turning non-numeric text into NA).
Then it creates ordered factors: wday\_fac maps weekday codes (or text
like ``Monday'') to ``Mon''--``Sun''; hour\_fac turns hours into an
ordered 0--23 factor; and month\_fac maps 1--12 to ``Jan''--``Dec'' (or
falls back to whatever strings exist). Finally, paid\_fac recodes the
numeric paid flag (0/1, with NA treated as 0) into a tidy two-level
factor ``Unpaid''/``Paid''. The result is a clean set of categorical
predictors with stable, meaningful levels for plots and regression.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{consumers =}\NormalTok{ fb}\SpecialCharTok{$}\NormalTok{lifetime\_post\_consumers,}
  \AttributeTok{paid =}\NormalTok{ paid\_fac,}
  \AttributeTok{wday =}\NormalTok{ wday\_fac,}
  \AttributeTok{hour=}\NormalTok{ hour\_fac,}
  \AttributeTok{month =}\NormalTok{ month\_fac,}
  \AttributeTok{idx =} \FunctionTok{seq\_len}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(fb))}
\NormalTok{)}

\FunctionTok{summary}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{consumers)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     9.0   332.5   551.5   798.8   955.5 11328.0
\end{verbatim}

This code builds the analysis tibble dat---it picks the response
(consumers) and the cleaned timing predictors (wday, hour, month), adds
the promotion flag (paid), and creates a simple time-order index (idx).
The summary(dat\$consumers) line quickly checks the outcome's
distribution; the output (min 9, Q1 ≈ 333, median ≈ 552, mean ≈ 799, Q3
≈ 956, max ≈ 11,328) shows a right-skewed variable with large upper
outliers, which motivates options like log1p(consumers) or robust SEs in
later models.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Question 1: Does the date and time in which a post is made impact the
engagement that said post receives?

We used log1p(consumers) because engagement counts are extremely
right-skewed with a few huge outliers, which compresses most points near
zero on the raw scale and can overly influence the fit. The log
transform (with the ``+1'' to safely handle zeros) stabilizes variance
and makes residuals closer to OLS assumptions, so estimates and p-values
are more reliable. It also improves readability of the scatter,
revealing patterns that raw counts hide. As a bonus, effects on the log
scale are easy to interpret approximately as percent changes on the
original scale.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot\_df }\OtherTok{\textless{}{-}}\NormalTok{ dat }\SpecialCharTok{|\textgreater{}} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{hour\_num =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{as.character}\NormalTok{(hour)))}

\FunctionTok{ggplot}\NormalTok{(plot\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ hour\_num, }\AttributeTok{y =} \FunctionTok{log1p}\NormalTok{(consumers))) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{shape =} \DecValTok{1}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.45}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.2}\NormalTok{, }\AttributeTok{position =} \FunctionTok{position\_jitter}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{height =} \DecValTok{0}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Point Plot with Best{-}Fit Line"}\NormalTok{,}
       \AttributeTok{subtitle =} \StringTok{"Engagement (log1p) vs Hour of Day"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Hour of Day (0–23)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"log(1 + Consumers)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{lab_deliverable_2_files/figure-latex/Q1-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wk\_map }\OtherTok{\textless{}{-}} \FunctionTok{setNames}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"Mon"}\NormalTok{,}\StringTok{"Tue"}\NormalTok{,}\StringTok{"Wed"}\NormalTok{,}\StringTok{"Thu"}\NormalTok{,}\StringTok{"Fri"}\NormalTok{,}\StringTok{"Sat"}\NormalTok{,}\StringTok{"Sun"}\NormalTok{))}
\NormalTok{plot\_df2 }\OtherTok{\textless{}{-}}\NormalTok{ dat }\SpecialCharTok{|\textgreater{}} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{wday\_num =} \FunctionTok{unname}\NormalTok{(wk\_map[}\FunctionTok{as.character}\NormalTok{(wday)]))}

\FunctionTok{ggplot}\NormalTok{(plot\_df2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ wday\_num, }\AttributeTok{y =} \FunctionTok{log1p}\NormalTok{(consumers))) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{shape =} \DecValTok{1}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.45}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.2}\NormalTok{, }\AttributeTok{position =} \FunctionTok{position\_jitter}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.15}\NormalTok{, }\AttributeTok{height =} \DecValTok{0}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{breaks =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\AttributeTok{labels =} \FunctionTok{names}\NormalTok{(wk\_map)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Point Plot with Best{-}Fit Line"}\NormalTok{,}
       \AttributeTok{subtitle =} \StringTok{"Engagement (log1p) vs Weekday"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Weekday"}\NormalTok{, }\AttributeTok{y =} \StringTok{"log(1 + Consumers)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{lab_deliverable_2_files/figure-latex/scatter_weekday_ols-1.pdf}}

\end{document}
